### ISSUE TITLE
Unable to find resource 'templates/generators/overviewFeatures.vm'

### ISSUE THREAD

**Issue by dipakkumar1225** [damianszczepanik/cucumber-reporting#1014]
In @After hook, I have added below code: 
```
File reportOutputDirectory = new File("target\\cucumber-reports");
List<String> jsonFiles = new ArrayList<>();
jsonFiles.add("target\\cucumber-reports\\CucumberTestReport.json");
String projectName = "cucumberProject";
Configuration configuration = new Configuration(reportOutputDirectory, projectName);
configuration.setNotFailingStatuses(Collections.singleton(Status.SKIPPED));
configuration.addReducingMethod(ReducingMethod.HIDE_EMPTY_HOOKS);
ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
reportBuilder.generateReports();
```

Below is error details.
Jul 17, 2021 10:05:10 PM net.masterthought.cucumber.ReportParser parseJsonFiles
INFO: File 'target\cucumber-reports\CucumberTestReport.json' contains 1 features
Jul 17, 2021 10:05:10 PM net.masterthought.cucumber.ReportBuilder generateErrorPage
INFO: Unexpected error
org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'templates/generators/overviewFeatures.vm'
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:452)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:335)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1102)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1077)
	at org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:528)
	at net.masterthought.cucumber.generators.AbstractPage.generateReport(AbstractPage.java:81)
	at net.masterthought.cucumber.generators.AbstractPage.generatePage(AbstractPage.java:66)
	at net.masterthought.cucumber.ReportBuilder.generatePages(ReportBuilder.java:156)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:103)
	at testutilities.listener.SampleCucumberPlugin.afterTestRun(SampleCucumberPlugin.java:116)
	at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
	at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
	at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunFinished(CucumberExecutionContext.java:93)
	at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:74)
	at io.cucumber.testng.TestNGCucumberRunner.finish(TestNGCucumberRunner.java:127)
	at io.cucumber.testng.AbstractTestNGCucumberTests.tearDownClass(AbstractTestNGCucumberTests.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

**Comment by damianszczepanik** [comment]
Looks like problem with location to resources,
https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/test/java/LiveDemoTest.java take this as reference
