### ISSUE TITLE
[5.6.0] Error parsing step comments

### ISSUE THREAD

**Issue by patrik-ronnqvist** [damianszczepanik/cucumber-reporting#1023]
The comments field in the Step class does not seem to be correct, at least not for all json report versions.

https://github.com/damianszczepanik/cucumber-reporting/blob/ae7872e70f087e2d009e108ebd36d8331605c40c/src/main/java/net/masterthought/cucumber/json/Step.java#L21

It expects a list of strings, like so:

```
"comments": [
  "comment1",
  "comment2",
  "comment3"
]
```

But in our case it's a list of objects, like so:

```
"comments": [
  {
	"line": 1,
	"value": "comment1"
  },
  {
	"line": 2,
	"value": "comment2"
  },
  {
	"line": 2,
	"value": "comment3"
  }
]
```

It produces the following error:

```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<java.lang.Object>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (InputStreamReader); line: 150, column: 15] (through reference chain: java.lang.Object[][0]->net.masterthought.cucumber.json.Feature["elements"]->java.lang.Object[][1]->net.masterthought.cucumber.json.Element["steps"]->java.lang.Object[][0]->net.masterthought.cucumber.json.Step["comments"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1280)
	at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:872)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:1281)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:216)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:182)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:214)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:24)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:214)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:24)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:214)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:24)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3561)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:93)
	... 13 more
```

It worked in Cucumber Reports version 5.5.4 (because the Step class did not have the comments field) but does not work in Cucumber Reports version 5.6.0.

Is this a known issue? Do we need to update Cucumber, JUnit, or something on our end?

**Comment by damianszczepanik** [comment]
@jfougere this looks like regression after
 Include step comments in report #1012

**Comment by jfougere** [comment]
Unfortunately it looks like so @damianszczepanik 

I added the support for comments thinking that this was not existing in cucumber reports, so I proposed as format what Karate was producing for its own report which is an array of string.

@patrik-ronnqvist could you please give some more information about what you use to produce your json report ? 
Cucumber ? Which version ? 

I'm not too sure but my understanding is that comments were removed from cucumber json formatter. @damianszczepanik  I suppose you know more about this than I do.

Once clarified we may have a few options:
- Support both formats
- Align Karate on previous cucumber format and switch to the cucumber format
- Only support Karate format and avoid failing when the format is not supported

@damianszczepanik  some thoughts ?

**Comment by patrik-ronnqvist** [comment]
@jfougere It's a java project that has the following dependencies (among others):

info.cukes:cucumber-java:1.2.5
info.cukes:cucumber-junit:1.2.5
info.cukes:cucumber-picocontainer:1.2.5
junit:junit:4.12

The feature files have # comments in them. The tests are run with the cucumber.api.junit.Cucumber and cucumber.api.CucumberOptions classes, like so:

```
@RunWith(Cucumber.class)
@CucumberOptions(
      tags = {"@smoke"},
      plugin = { "pretty", "html:report/cucumber", "json:report/cucumber_json/smoke.json" },
      strict = true, monochrome = true, glue = { "stepdefinitions", "runners"},
      features = "src/main/resources/features/smoke/")
public class SmokeRunner
{
}
```

**Comment by jfougere** [comment]
@patrik-ronnqvist could you try upgrading your dependencies ? 

On my side I have a working project with:
io.cucumber:cucumber-java:2.3.1
io.cucumber:cucumber-junit:2.3.1
io.cucumber:cucumber-spring:2.3.1
io.cucumber:cucumber-java8:2.3.1

I will let @damianszczepanik advise if we need to support your version.

**Comment by patrik-ronnqvist** [comment]
@jfougere I'm trying, but I'm having trouble with some API changes. It's used in some test code that scans the feature files before running them and prepares the testing environment.

RuntimeOptions.cucumberFeatures() now requires an EventBus parameter. Where do you get that from? Are you supposed to implement one? It doesn't look like you can just send in null.

CucumberFeature.getFeatureElements() is missing, and I can't find an equivalent. It's supposed to return a list of CucumberTagStatement.

**Comment by jfougere** [comment]
@jfougere sure I can give it a try. However I need to check how you manage different format.
