### ISSUE TITLE
net.masterthought.cucumber.ValidationException: Passed files have no features Error

### ISSUE THREAD

**Issue by harihere** [damianszczepanik/cucumber-reporting#1033]
The exception is displayed while generating the report 

JSON file which is generated has only [ ] as the value  

_Cucumber version: 7.0.0 | Selenium : 4:0:0_

**_Runner class_** 

```
@CucumberOptions(plugin = {"json:target/cucumber-report/cucumber.json",
                           "pretty","html:target/site/cucumber-pretty.html"},

        features = {"src/test/resources/features"},
        tags = "Test1",
        glue = {"stepDefinitions"},
        monochrome = true)

public class TestRunner extends AbstractTestNGCucumberTests {

    private static final Logger logger = LogManager.getLogger(TestRunner.class);
    private TestNGCucumberRunner testNGCucumberRunner;

    @Override
    @DataProvider(parallel = false)
    public Object[][] scenarios() {
        return super.scenarios();
    }

    @BeforeClass(alwaysRun = true)
    public void setUpClass() throws Exception {
        testNGCucumberRunner = new TestNGCucumberRunner(this.getClass());
    }

    @Override
    @AfterClass(alwaysRun = true)
    public void tearDownClass() {
        testNGCucumberRunner.finish();
    }
}
```

POM -- > 
```
  <plugin>
                    <groupId>net.masterthought</groupId>
                    <artifactId>maven-cucumber-reporting</artifactId>
                    <version>5.6.1</version>
                    <executions>
                        <execution>
                            <id>execution</id>
                            <goals>
                                <goal>generate</goal>
                            </goals>
                                                        <phase>verify</phase>
                            <configuration>
                                <projectName>${project.name}</projectName>
                                <skip>false</skip>
                                                             <outputDirectory>${project.build.directory}/cucumber-report</outputDirectory>
                               
                                <inputDirectory>${project.build.directory}</inputDirectory>
                                <jsonFiles>
                      
                                    <param>**/*.json</param>
                                </jsonFiles>
                                <mergeFeaturesById>false</mergeFeaturesById>
                                                              <mergeFeaturesWithRetest>false</mergeFeaturesWithRetest>
                                                    <checkBuildResult>false</checkBuildResult>
                            </configuration>
                        </execution>
                    </executions>
                          </plugin>
            <plugin>
```

**_Exception :_** 

net.masterthought.cucumber.ReportBuilder generateErrorPage
INFO: Unexpected error
net.masterthought.cucumber.ValidationException: Passed files have no features!
        at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:79)
        at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:97)
        at net.masterthought.cucumber.CucumberReportGeneratorMojo.execute(CucumberReportGeneratorMojo.java:222)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

**Comment by damianszczepanik** [comment]
Passed files have no features! - files which you are passing have no features, cat then and review
