### ISSUE TITLE
java.lang.IllegalArgumentException: No enum constant

### ISSUE THREAD

**Issue by FabHt** [damianszczepanik/cucumber-reporting#1084]
Hello,

This error occurs with a Jenkin 2.361.4 : 

[CucumberReport] Using Cucumber Reports version 5.7.4
[CucumberReport] JSON report directory is ""
[CucumberReport] Copied 11 properties files from workspace "D:\Jenkins\workspace\CI_SELENIUM\Selenium CGT\SELENIUM_CGT" to reports directory "D:\Jenkins\home\jobs\CI_SELENIUM\jobs\Selenium CGT\jobs\SELENIUM_CGT\builds\4497\cucumber-html-reports\.cache"
[CucumberReport] Copied 1 files from workspace "D:\Jenkins\workspace\CI_SELENIUM\Selenium CGT\SELENIUM_CGT" to reports directory "D:\Jenkins\home\jobs\CI_SELENIUM\jobs\Selenium CGT\jobs\SELENIUM_CGT\builds\4497\cucumber-html-reports\.cache"
[CucumberReport] Processing 1 json files:
[CucumberReport] D:\Jenkins\home\jobs\CI_SELENIUM\jobs\Selenium CGT\jobs\SELENIUM_CGT\builds\4497\cucumber-html-reports\.cache\target\cucumber.json
ERROR: Build step failed with exception
java.lang.IllegalArgumentException: No enum constant net.masterthought.cucumber.sorting.SortingMethod.
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at net.masterthought.cucumber.sorting.SortingMethod.valueOf(SortingMethod.java:8)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:523)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:434)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:816)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:765)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1073)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:709)
	at hudson.model.Run.execute(Run.java:1924)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:107)
	at hudson.model.Executor.run(Executor.java:449)
Build step 'Cucumber reports' marked build as failure
Finished: FAILURE

In fact it occures on previous releases too, but upgrade of Jenkins and plugins has not corrected this issue.

Any Ideas?

Best regards,

**Comment by damianszczepanik** [comment]
Problem is related to configuration you have on your Jenkins and not with library itself

**Comment by FabHt** [comment]
Could you please give the information that lead you to this conclusion?

**Comment by damianszczepanik** [comment]
Because this report i generated properly http://damianszczepanik.github.io/cucumber-html-reports/overview-features.html
