### ISSUE TITLE
Not to build html reports, exception NoSuchMethodError

### ISSUE THREAD

**Issue by saikrishna321** [damianszczepanik/cucumber-reporting#382]
@damianszczepanik when i try to build the report i get the below exception, using the latest version

```
java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.sizeOf(Ljava/io/File;)J

	at net.masterthought.cucumber.ReportParser.parseJsonResults(ReportParser.java:36)
	at net.masterthought.cucumber.ReportParser.<init>(ReportParser.java:24)
	at net.masterthought.cucumber.ReportBuilder.<init>(ReportBuilder.java:196)
	at cucumber.parallel.HtmlReporter.generateReports(HtmlReporter.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

<h2>Code Sample</h2>

https://gist.github.com/saikrishna321/23182640eb13292972ea

target folder has two .json files as in the gist below 

<h2>Sample JSON</h2>

https://gist.github.com/saikrishna321/70dc6ac45cdc4624c220

https://gist.github.com/saikrishna321/483a28937249849ba997

**Comment by damianszczepanik** [comment]
You're using old version  - upgrade and try again
