### ISSUE TITLE
Version 2.2 cannot generate HTML from some "valid" JSON

### ISSUE THREAD

**Issue by RussellKeane** [damianszczepanik/cucumber-reporting#436]
Hi,

Version 2.2 of the cucumber-reporting plugin appears unable to generate the HTML for some JSON where version 2.1 of the cucumber-reporting plugin could.

We are using Jenkins v2.1.

The following file is a sample problematic json file (renamed to .txt for upload):
[reports_v15.json.txt](https://github.com/damianszczepanik/cucumber-reporting/files/246872/reports_v15.json.txt)

The job console output is as follows:
```
Started by user Administrator
[EnvInject] - Loading node environment variables.
Building remotely on xxxxxxxx in workspace W:\workspace\test_cucumber
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] Copying all json files from slave: w:\a to master reports directory: D:\Jenkins\jobs\test_cucumber\builds\6\cucumber-html-reports
[CucumberReportPublisher] Found 1 json files.
[CucumberReportPublisher] 1. Found a json file: reports_v15.json
[CucumberReportPublisher] Generating HTML reports
Build step 'Cucumber-JVM reports' changed build result to FAILURE
Finished: FAILURE
```

And the Jenkins system log shows the job as running to completion (no java exceptions).

Reverting to Version 2.1 of the cucumber-reporting plugin resolves the issue.

If there's anything I can do to assist in re-creating the issue, please let me know.

**Comment by RussellKeane** [comment]
Apologies, I forgot to add that when clicking on the "Cucumber-jvm reports" link within the job, I get the following exception:

```
Error
Something went wrong with project test_cucumber, build 16

java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
	at net.masterthought.cucumber.json.Step.elementToString(Step.java:133)
	at net.masterthought.cucumber.json.Step.calculateOutputs(Step.java:120)
	at net.masterthought.cucumber.json.Step.setMedaData(Step.java:97)
	at net.masterthought.cucumber.json.Element.setMedaData(Element.java:114)
	at net.masterthought.cucumber.json.Feature.setMetaData(Feature.java:147)
	at net.masterthought.cucumber.ReportParser.setMetadata(ReportParser.java:51)
	at net.masterthought.cucumber.ReportParser.parseJsonResults(ReportParser.java:37)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:56)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:134)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Trying to generate report from following files. Make sure they are valid cucumber report files:
           D:\\Jenkins\jobs\test_cucumber\builds\6\cucumber-html-reports\reports_v15.json
```

**Comment by damianszczepanik** [comment]
This does not seem to be valid cucumber-jvm format:

``
            "output": [
              "Record patient_1 contains:",
              {
                "operat_id": 666,
                "dt": "2016-04-26 13:49:32 +0100",
                "ty": 1,
                "id": 382,
                "auditseq": 826922223,
                "surname": "test",
                "forename1": "test1"
              }
            ],
``
``

**Comment by RussellKeane** [comment]
Hmm.
I'll double check in the morning exactly the calls we make but the report was generated directly using cucumber, although not the very latest version thereof.

Also, the very same report worked perfectly with version 2.1 of the plugin. Did the report format handling change in the latest version?

**Comment by damianszczepanik** [comment]
Rather not

**Comment by damianszczepanik** [comment]
How would you like to display such output?

**Comment by cristim** [comment]
We recently updated from an ancient 1.2.0 to the latest 2.8.0 and we see a similar error after the update.

I'll dig deeper into it, but I would like to know if you guys found any fix for this one.

**Comment by damianszczepanik** [comment]
@cristim can you show me your JSON report?
