### ISSUE TITLE
Could not parse build number: ${${build.number}}

### ISSUE THREAD

**Issue by Gashzilla** [damianszczepanik/cucumber-reporting#442]
I'm running from Jenkins. The reporting capability is working great if I DON'T specify a Json reports path, which I confirmed on a project containing only xml files. However, when I set that path (because the project I'm working on has numerous .json files (and errored out when trying to find the right one to use), I get the error as specified in the title. Here is the full text of the error:

Could not parse build number: ${${build.number}}.
java.lang.NumberFormatException: For input string: "${${build.number}}"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_66]
	at java.lang.Integer.parseInt(Integer.java:569) ~[?:1.8.0_66]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_66]
	at net.masterthought.cucumber.generators.AbstractPage.buildGeneralParameters(AbstractPage.java:96) [cucumber-reporting-2.0.0.jar:?]
	at net.masterthought.cucumber.generators.AbstractPage.<init>(AbstractPage.java:45) [cucumber-reporting-2.0.0.jar:?]
	at net.masterthought.cucumber.generators.FeatureOverviewPage.<init>(FeatureOverviewPage.java:9) [cucumber-reporting-2.0.0.jar:?]
	at net.masterthought.cucumber.ReportBuilder.generateAllPages(ReportBuilder.java:66) [cucumber-reporting-2.0.0.jar:?]
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:51) [cucumber-reporting-2.0.0.jar:?]
	at net.masterthought.cucumber.CucumberReportGeneratorMojo.execute(CucumberReportGeneratorMojo.java:125) [maven-cucumber-reporting-2.0.0.jar:?]
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132) [maven-core-3.2.2.jar:3.2.2]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208) [maven-core-3.2.2.jar:3.2.2]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) [maven-core-3.2.2.jar:3.2.2]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) [maven-core-3.2.2.jar:3.2.2]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116) [maven-core-3.2.2.jar:3.2.2]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80) [maven-core-3.2.2.jar:3.2.2]
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) [maven-core-3.2.2.jar:3.2.2]
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120) [maven-core-3.2.2.jar:3.2.2]
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347) [maven-core-3.2.2.jar:3.2.2]
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154) [maven-core-3.2.2.jar:3.2.2]
	at org.jvnet.hudson.maven3.launcher.Maven31Launcher.main(Maven31Launcher.java:132) [maven31-interceptor-1.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330) [plexus-classworlds-2.5.1.jar:?]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238) [plexus-classworlds-2.5.1.jar:?]
	at jenkins.maven3.agent.Maven31Main.launch(Maven31Main.java:181) [maven31-agent-1.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:136) [?:?]
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:71) [?:?]
	at hudson.remoting.UserRequest.perform(UserRequest.java:120) [remoting-2.53.2.jar:?]
	at hudson.remoting.UserRequest.perform(UserRequest.java:48) [remoting-2.53.2.jar:?]
	at hudson.remoting.Request$2.run(Request.java:326) [remoting-2.53.2.jar:?]
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68) [remoting-2.53.2.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

**Comment by damianszczepanik** [comment]
I see you are using the old version of the plugin so you may upgrade and check or wait a few days because this method is changed in recent days and will be released soon.
