### ISSUE TITLE
NoSuchMethodError when used with Spring Boot

### ISSUE THREAD

**Issue by oltruong** [damianszczepanik/cucumber-reporting#481]
Hi I have the following issue when using the 2.5.0 version with Spring Boot.

```
2016-06-20 16:32:39.664 ERROR 6332 --- [nio-8082-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.info(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V] with root cause
java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.info(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V
	at net.masterthought.cucumber.ReportParser.parseJsonResults(ReportParser.java:60) ~[cucumber-reporting-2.5.0.jar:na]
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:51) ~[cucumber-reporting-2.5.0.jar:na]
```

I've tried with Spring Boot 1.3.5 and even 1.4.0.M3, still have the issue.

In 2.3.0 everything was fine.

It looks like a version conflict in logger but I can't see what's wrong.

**Comment by damianszczepanik** [comment]
Not sure what is the problem (maybe old dependencies of Spring boot) but https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/ReportParser.java#L60 uses https://logging.apache.org/log4j/2.0/log4j-api/apidocs/org/apache/logging/log4j/Logger.html#info(java.lang.String,%20java.lang.Object,%20java.lang.Object)

**Comment by oltruong** [comment]
Thanks for your feedback. If I add directly the class in my source code it works though...
