### ISSUE TITLE
Exceptions thrown when executing code in usage section.

### ISSUE THREAD

**Issue by balajir2016** [damianszczepanik/cucumber-reporting#564]
Added the below dependency in my POM file

<dependency>
    		<groupId>net.masterthought</groupId>
    		<artifactId>cucumber-reporting</artifactId>
    		<version>3.2.0</version>
</dependency>

Below is the exception I get when I execute the code you have mentioned in the usage. Please let me know what I am missing.

ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang/text/StrBuilder
	at org.apache.velocity.runtime.parser.ParserTokenManager.<init>(ParserTokenManager.java:5161)
	at org.apache.velocity.runtime.parser.Parser.<init>(Parser.java:3497)
	at org.apache.velocity.runtime.parser.Parser.<init>(Parser.java:64)
	at org.apache.velocity.runtime.RuntimeInstance.createNewParser(RuntimeInstance.java:1130)
	at org.apache.velocity.runtime.ParserPoolImpl.initialize(ParserPoolImpl.java:50)
	at org.apache.velocity.runtime.RuntimeInstance.initializeParserPool(RuntimeInstance.java:1103)
	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:266)
	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:646)
	at org.apache.velocity.app.VelocityEngine.init(VelocityEngine.java:116)
	at net.masterthought.cucumber.generators.AbstractPage.<init>(AbstractPage.java:49)
	at net.masterthought.cucumber.generators.ErrorPage.<init>(ErrorPage.java:18)
	at net.masterthought.cucumber.ReportBuilder.generateErrorPage(ReportBuilder.java:196)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:86)
	at PrettyReport.main(PrettyReport.java:31)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.text.StrBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import net.masterthought.cucumber.Configuration;
import net.masterthought.cucumber.ReportBuilder;
import net.masterthought.cucumber.Reportable;

public class PrettyReport {

	public static void main(String[] args) 
	{
		
		File reportOutputDirectory = new File("target");
		List<String> jsonFiles = new ArrayList<String>();
		jsonFiles.add("cucumber-report.json");
		//jsonFiles.add("cucumber-report-2.json");

		String buildNumber = "1";
		String projectName = "cucumberProject";
		boolean runWithJenkins = false;
		boolean parallelTesting = false;

		Configuration configuration = new Configuration(reportOutputDirectory, projectName);
		// optional configuration
		configuration.setParallelTesting(parallelTesting);
		configuration.setRunWithJenkins(runWithJenkins);
		configuration.setBuildNumber(buildNumber);

		ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
		Reportable result = reportBuilder.generateReports();
		
		

	}

}

**Comment by damianszczepanik** [comment]
Does not look like the problem with configuration but rather dependency you have in your pom.xml file
