### ISSUE TITLE
Premature end of file - error parsing log4j file

### ISSUE THREAD

**Issue by gaganangrish** [damianszczepanik/cucumber-reporting#633]
Upon running the below code with attached Cucumber json files, I am getting log4j error
`

	public static void main(String[] args) {
		try {
			File reportOutputDirectory = new File("target");
			List<String> jsonFiles = new ArrayList<String>();
			jsonFiles.add("cucumber1.json");
			jsonFiles.add("cucumber2.json");
			jsonFiles.add("cucumber3.json");

			String buildNumber = "1";
			String projectName = "cucumberProject";
			boolean runWithJenkins = false;
			boolean parallelTesting = true;

			Configuration configuration = new Configuration(reportOutputDirectory, projectName);
			// optional configuration
			configuration.setParallelTesting(parallelTesting);
			configuration.setRunWithJenkins(runWithJenkins);
			configuration.setBuildNumber(buildNumber);
			// addidtional metadata presented on main page
			configuration.addClassifications("Platform", "Windows");
			configuration.addClassifications("Browser", "Chrome");
			configuration.addClassifications("Branch", "QA");

			ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
			Reportable result = reportBuilder.generateReports();
			// and here validate 'result' to decide what to do
			// if report has failed features, undefined steps etc
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
`
[cucumber2.txt](https://github.com/damianszczepanik/cucumber-reporting/files/1024556/cucumber2.txt)
[cucumber1.txt](https://github.com/damianszczepanik/cucumber-reporting/files/1024557/cucumber1.txt)
[cucumber3.txt](https://github.com/damianszczepanik/cucumber-reporting/files/1024558/cucumber3.txt)

the error log is:
`[Fatal Error] :-1:-1: Premature end of file.
ERROR StatusLogger Error parsing C:\---\----\-----\target\classes\log4j2.xml
 org.xml.sax.SAXParseException; Premature end of file.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at org.apache.logging.log4j.core.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:95)
	at org.apache.logging.log4j.core.config.xml.XmlConfigurationFactory.getConfiguration(XmlConfigurationFactory.java:46)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:522)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:459)
	at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:265)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:613)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
	at net.masterthought.cucumber.ReportBuilder.<clinit>(ReportBuilder.java:37)
	at reporter.Reporter.main(Reporter.java:36)
ERROR StatusLogger No logging configuration
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.lang3.math.NumberUtils.isCreatable(Ljava/lang/String;)Z
	at net.masterthought.cucumber.generators.AbstractPage.buildGeneralParameters(AbstractPage.java:113)
	at net.masterthought.cucumber.generators.AbstractPage.<init>(AbstractPage.java:52)
	at net.masterthought.cucumber.generators.ErrorPage.<init>(ErrorPage.java:18)
	at net.masterthought.cucumber.ReportBuilder.generateErrorPage(ReportBuilder.java:230)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:103)
	at reporter.Reporter.main(Reporter.java:37)`

Can you please have a look if I am doing something wrong of if it's a bug in the repo. Thanks.

**Comment by damianszczepanik** [comment]
There is something wrong with the configuration for logger but rather not cucumber-reporting itself

**Comment by gaganangrish** [comment]
Thanks @damianszczepanik , is there a workaround for this? Or can you disable logger from your code?

**Comment by damianszczepanik** [comment]
As I said this out of the scope of this project so I don't see reason for the update and the workaround should be done probably in your pom where you have defined loggers or you import them via dependencies.
