### ISSUE TITLE
Getting error while generating report

### ISSUE THREAD

**Issue by tariqueahmed89** [damianszczepanik/cucumber-reporting#670]
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
[TestNG] Reporter com.compareglobalgroup.listeners.CucumberReporter@7f829c76 failed
org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource '/templates/headers.vm'
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:458)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:341)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:831)
	at org.apache.velocity.runtime.directive.Parse.render(Parse.java:141)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:114)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:230)
	at org.apache.velocity.Template.merge(Template.java:256)
	at net.masterthought.cucumber.generators.AbstractPage.generateReport(AbstractPage.java:70)
	at net.masterthought.cucumber.generators.AbstractPage.generatePage(AbstractPage.java:55)
	at net.masterthought.cucumber.ReportBuilder.generateErrorPage(ReportBuilder.java:194)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:86)
	at com.compareglobalgroup.reporting.CucumberReporting.generateCucumberReport(CucumberReporting.java:43)
	at com.compareglobalgroup.listeners.CucumberReporter.generateReport(CucumberReporter.java:43)
	at org.testng.TestNG.generateReports(TestNG.java:1192)
	at org.testng.TestNG.run(TestNG.java:1120)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)

**Comment by tariqueahmed89** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.compareglobalgroup</groupId>
	<artifactId>automation</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<suiteXmlFile>cucumber_testng.xml</suiteXmlFile>
		<skipTests>false</skipTests>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.11</version>
			<scope>compile</scope>
		</dependency>


		<dependency>
			<groupId>org.uncommons</groupId>
			<artifactId>reportng</artifactId>
			<version>1.1.4</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.velocity</groupId>
					<artifactId>velocity</artifactId>
				</exclusion>
				
			
				
			</exclusions>
		</dependency>

		<dependency>
			<groupId>com.google.inject</groupId>
			<artifactId>guice</artifactId>
			<version>4.1.0</version>
		</dependency>

		<dependency>
			<groupId>velocity</groupId>
			<artifactId>velocity</artifactId>
			<version>1.5</version>
			<type>pom</type>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.2.5</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-testng</artifactId>
			<version>1.2.5</version>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.5.3</version>
		</dependency>

		

		<dependency>
			<groupId>net.sourceforge.jexcelapi</groupId>
			<artifactId>jxl</artifactId>
			<version>2.6</version>
		</dependency>

		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>1.4</version>
		</dependency>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.0</version>
		</dependency>

		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>23.0</version>
		</dependency>

		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>3.1.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.velocity</groupId>
			<artifactId>velocity</artifactId>
			<version>1.7</version>
		</dependency>

	






	</dependencies>

	<build>
		<plugins>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.20.1</version>
				<configuration>
					
					
					<suiteXmlFiles>
						<suiteXmlFile>${suiteXmlFile}</suiteXmlFile>
					</suiteXmlFiles>
					
					<skipTests>${skipTests}</skipTests>
					<testFailureIgnore>true</testFailureIgnore>
					<systemPropertyVariables>
						<browser>FF</browser>
						<execution>local</execution>
					</systemPropertyVariables>
				</configuration>
			</plugin>

		</plugins>
	</build>

</project>

**Comment by damianszczepanik** [comment]
I believe there is something wrong with how you run the project as the template from resources could not be found. Try to run tests from this project and find differences.
