### ISSUE TITLE
Cucumber-report plugin 

### ISSUE THREAD

**Issue by Vikas1712** [damianszczepanik/cucumber-reporting#687]
After job execution, I am getting this error. The prob;em is cucumber.json is not getting created.

net.masterthought.cucumber.ValidationException: No report file was added!
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:55)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:90)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:300)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:229)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:682)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:627)
	at hudson.model.Run.execute(Run.java:1762)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)

pls help about this

**Comment by Vikas1712** [comment]
@CucumberOptions(
        plugin = { 
                "html:target/cucumber-html-report",
                "json:target/cucumber.json"
        },features ={"./sample.feature"},
            glue ={"com/automation/steps"},
            strict = true,
            dryRun= false,monochrome = true)

public class Runner {

	@Test
	public void runcukes(){
		System.out.println("I am in runner.");
		new TestNGCucumberRunner(getClass()).runCukes();
	}
	
	@AfterClass
    public static void generateReport(){
       File reportOutputDirectory = new File("target");
       List<String> jsonFiles = new ArrayList<>();
       jsonFiles.add("target/cucumber.json");

       String jenkinsBasePath = "";
       String buildNumber = "1";
       String projectName = "AutomationFrameworkCucumber";
       boolean skippedFails = true;
       boolean pendingFails = false;
       boolean undefinedFails = true;
       boolean missingFails = true;
       boolean runWithJenkins = false;
       boolean parallelTesting = false;

       Configuration configuration = new Configuration(reportOutputDirectory, projectName);
       // optionally only if you need
       //configuration.setStatusFlags(skippedFails, pendingFails, undefinedFails, missingFails);
       configuration.setParallelTesting(parallelTesting);
       //configuration.setJenkinsBasePath(jenkinsBasePath);
       configuration.setRunWithJenkins(runWithJenkins);
       configuration.setBuildNumber(buildNumber);

       ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
       reportBuilder.generateReports();
   }

This is my runner class.

**Comment by AniruddhSolanki** [comment]
try this
`jsonFiles.add(System.getProperty("user.dir")+"\\target\\cucumber.json");`

**Comment by iranicus** [comment]
I seem to be stuck on the same issue, was there a solution to this found?
