### ISSUE TITLE
ERROR: Step ‘Cucumber reports’ aborted due to exception: 

### ISSUE THREAD

**Issue by Android1029** [damianszczepanik/cucumber-reporting#710]
ERROR: Step ‘Cucumber reports’ aborted due to exception: 
java.lang.SecurityException: Rejected: org.apache.tools.ant.Location; see https://jenkins.io/redirect/class-filter/
	at hudson.remoting.ClassFilter.check(ClassFilter.java:76)
	at hudson.remoting.MultiClassLoaderSerializer$Input.resolveClass(MultiClassLoaderSerializer.java:129)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1826)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at hudson.remoting.UserRequest.deserialize(UserRequest.java:277)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
	at hudson.remoting.Channel$2.adapt(Channel.java:986)
	at hudson.remoting.Channel$2.adapt(Channel.java:983)
	at hudson.remoting.FutureAdapter.get(FutureAdapter.java:55)
	at hudson.FilePath.copyRecursiveTo(FilePath.java:2292)
Caused: java.io.IOException
	at hudson.FilePath.copyRecursiveTo(FilePath.java:2296)
	at hudson.FilePath.copyRecursiveTo(FilePath.java:2180)
	at hudson.FilePath.copyRecursiveTo(FilePath.java:2163)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:258)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:229)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1752)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE

**Comment by damianszczepanik** [comment]
Duplicate of https://github.com/jenkinsci/cucumber-reports-plugin/issues/227

**Comment by BALAJINAMMAZHWAR** [comment]
Waiting for Jenkins to finish collecting data
[JENKINS] Archiving C:\Users\PRIYABALA\eclipse-workspace\CucumberAdactin\pom.xml to com/CucumberAdactin/0.0.1-SNAPSHOT/CucumberAdactin-0.0.1-SNAPSHOT.pom
[JENKINS] Archiving C:\Users\PRIYABALA\eclipse-workspace\CucumberAdactin\target\CucumberAdactin-0.0.1-SNAPSHOT.jar to com/CucumberAdactin/0.0.1-SNAPSHOT/CucumberAdactin-0.0.1-SNAPSHOT.jar
channel stopped
C:\ProgramData\Jenkins\.jenkins\workspace
ERROR: Step ‘Cucumber Trend Report’ aborted due to exception: 
java.io.FileNotFoundException: File system element for parameter 'source' does not exist: 'C:\ProgramData\Jenkins\.jenkins\workspace\Adactin\CucumberAdactinReports\Cucumber_Adactin_Trend'
	at org.apache.commons.io.FileUtils.requireExistsChecked(FileUtils.java:2719)
	at org.apache.commons.io.FileUtils.requireFileCopy(FileUtils.java:2751)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:840)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:756)
	at org.jenkinsci.plugins.cucumbertrendsreport.publish.CucumberTrendReportBuilder.perform(CucumberTrendReportBuilder.java:70)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1072)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:711)
	at hudson.model.Run.execute(Run.java:1925)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:107)
	at hudson.model.Executor.run(Executor.java:449)
[CucumberReport] Using Cucumber Reports version 5.7.4
[CucumberReport] JSON report directory is "C:\Users\PRIYABALA\eclipse-workspace\CucumberAdactin\Reports"
[CucumberReport] Copied 0 properties files from workspace "C:\Users\PRIYABALA\eclipse-workspace\CucumberAdactin\Reports" to reports directory "C:\ProgramData\Jenkins\.jenkins\jobs\Adactin\builds\11\cucumber-html-reports_c4320ea1-79c2-3935-b1f0-482b69034243\.cache"
[CucumberReport] Copied 1 files from workspace "C:\Users\PRIYABALA\eclipse-workspace\CucumberAdactin\Reports" to reports directory "C:\ProgramData\Jenkins\.jenkins\jobs\Adactin\builds\11\cucumber-html-reports_c4320ea1-79c2-3935-b1f0-482b69034243\.cache"
[CucumberReport] Processing 1 json files:
[CucumberReport] C:\ProgramData\Jenkins\.jenkins\jobs\Adactin\builds\11\cucumber-html-reports_c4320ea1-79c2-3935-b1f0-482b69034243\.cache\jsonfile.json
Finished: FAILURE



hi frndz please give a solution for this error, thanks in advance
