### ISSUE TITLE
Transitive Dependency Conflict with org.apache.velocity:velocity

### ISSUE THREAD

**Issue by cnadukula** [damianszczepanik/cucumber-reporting#719]
Hi, I am using mockserver-client-java(5.3.0) which has a transitive dependency of org.apache.velocity:velocity-engine-scripting:2.0 and i notice that your code has a dependency on org.apache.velocity:velocity:1.7. So when i try to generate a report, it fails since there is conflict between the two. 

StackTrace:
at org.apache.velocity.Template.merge(Template.java:264)
	at net.masterthought.cucumber.generators.AbstractPage.generateReport(AbstractPage.java:77)
	at net.masterthought.cucumber.generators.AbstractPage.generatePage(AbstractPage.java:58)
	at net.masterthought.cucumber.ReportBuilder.generatePages(ReportBuilder.java:151)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:98)
_---------------_
Exception in thread "main" java.lang.AbstractMethodError: net.masterthought.cucumber.generators.EscapeHtmlReference.referenceInsert(Lorg/apache/velocity/context/Context;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
	at org.apache.velocity.app.event.EventCartridge.referenceInsert(EventCartridge.java:280)
	at org.apache.velocity.app.event.EventHandlerUtil.referenceInsert(EventHandlerUtil.java:64)
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:446)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:144)
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:194)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:323)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:254)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:295)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:377)
	at org.apache.velocity.Template.merge(Template.java:359)

Is this a known issue? if yes, how to resolve this? Please advise ASAP. 

thanks,
Chandra

**Comment by cnadukula** [comment]
ok, I was able to solve the issue. **_mockserver-client-java_** starting using velocity dependency since their version 4.0.0. so by downgrading to version 3.12, i was able to print the report with no issues. But please let me know if you guys plan to address this problem, so i can upgrade the version of mock-server-client on my end.

**Comment by damianszczepanik** [comment]
If you have conflict with lib you can solve it by excluding one which is with conflict.
