### ISSUE TITLE
FileNotFoundException when generate report

### ISSUE THREAD

**Issue by AniruddhSolanki** [damianszczepanik/cucumber-reporting#736]
Following is the code,

`
File reportOutputDirectory = new File("D:\\AA_Automation\\target");

        List<String> jsonFiles = new ArrayList<>();

        jsonFiles.add("cucumber-report.json");

        String buildNumber = "1";
        String projectName = "cucumberProject";
        boolean runWithJenkins = false;
        boolean parallelTesting = false;
        Configuration configuration = new Configuration(reportOutputDirectory, projectName);

        configuration.setParallelTesting(parallelTesting);
        configuration.setRunWithJenkins(runWithJenkins);
        configuration.setBuildNumber(buildNumber);

        configuration.addClassifications("Platform", "Windows");
        configuration.addClassifications("Browser", "Firefox");
        configuration.addClassifications("Branch", "release/1.0");
        System.out.println(configuration.getReportDirectory());
        ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
        reportBuilder.generateReports();
`

When I run this I get below error.

> Jul 02, 2018 6:37:59 PM net.masterthought.cucumber.ReportBuilder generateErrorPage
INFO: Unexpected error
net.masterthought.cucumber.ValidationException: java.io.FileNotFoundException: cucumber-report.json (The system cannot find the file specified)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:93)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:61)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:88)
	at com.AA.AutomationUtil.CucumberReporter.main(CucumberReporter.java:41)
Caused by: java.io.FileNotFoundException: cucumber-report.json (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:83)
	... 3 more

**Comment by damianszczepanik** [comment]
This is problem with the path you've provided

> The system cannot find the file specified
