### ISSUE TITLE
Code Fails In When Run In Jenkins

### ISSUE THREAD

**Issue by jhammell** [damianszczepanik/cucumber-reporting#746]
This error is thrown when run in by the Jenkins plugin only.  I have a pull request #745 pending which corrects the error:

ERROR: Step ?Cucumber reports? aborted due to exception:

java.lang.NoSuchMethodError: org.apache.commons.lang3.math.NumberUtils.isCreatable(Ljava/lang/String;)Z
            at net.masterthought.cucumber.generators.AbstractPage.buildGeneralParameters(AbstractPage.java:114)
            at net.masterthought.cucumber.generators.AbstractPage.<init>(AbstractPage.java:52)
            at net.masterthought.cucumber.generators.FeaturesOverviewPage.<init>(FeaturesOverviewPage.java:12)
            at net.masterthought.cucumber.ReportBuilder.generatePages(ReportBuilder.java:151)
            at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:98)
            at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:300)
            at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:229)
            at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
            at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
            at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
            at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
            at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1073)
            at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
            at hudson.model.Run.execute(Run.java:1749)
            at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
            at hudson.model.ResourceController.execute(ResourceController.java:97)
            at hudson.model.Executor.run(Executor.java:429)

**Comment by damianszczepanik** [comment]
Yes, looks like duplicate but I'm not sure when this case happens

**Comment by damianszczepanik** [comment]
Pull request was not completed, closing this
