### ISSUE TITLE
net.masterthought.cucumber.ValidationException: No report file was added!

### ISSUE THREAD

**Issue by Nikhilgupta1891** [damianszczepanik/cucumber-reporting#795]
This is the error I'm getting while generating Cucumber report - 

net.masterthought.cucumber.ValidationException: No report file was added!
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:55)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:90)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:300)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:229)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

Here is my method - 

void generateCucumberReport(String karateOutPath) {
        Collection<File> listOfjsonFiles = FileUtils.listFiles(new File(karateOutPath), new String[] {"json"}, true);
        List<String> listOfJsonPaths = new ArrayList(listOfjsonFiles.size());
        for (File eachFile : listOfjsonFiles) {
          listOfJsonPaths.add(eachFile.getAbsolutePath());
        }
        Configuration configur = new Configuration(new File("target"), "karate");
        ReportBuilder reportBuilder = new ReportBuilder(jsonPaths, configur);
        reportBuilder.generateReports();
      }

POM - 

<maven-cucumber-version>3.8.0</maven-cucumber-version>
 <dependency>
            <groupId>net.masterthought</groupId>
            <artifactId>maven-cucumber-reporting</artifactId>
            <version>${maven-cucumber-version}</version>
            <scope>test</scope>
        </dependency>

Where should I look at to find the solution?

**Comment by damianszczepanik** [comment]
The error message is quite descriptive and you might not read documentation with sample configuration.

**Comment by Nikhilgupta1891** [comment]
What changes do I need to make in the sample configuration to make Jenkins read and generate the report?

**Comment by Downright-Development** [comment]
Respectfully, @damianszczepanik, the error message isn’t always clear.  For example, I’ve seen this error reported if the results.json file it analyzes is also an empty file. 

@Nikhilgupta1891 I’d ensure the result file the plugin is analyzing actually has the correct content. (The results from running the tests)

**Comment by Nikhilgupta1891** [comment]
@Downright-Development - Where are these results.json generally stored/saved/created? 
From the config I mentioned above, is it in "target/surefire-reports" folder? (given karateOutPath = "target/surefire-reports")
When I run mvn clean install locally, I see 
* .txt
* .html
* .xml
files generated for the 1 feature I wrote.

**Comment by Downright-Development** [comment]
@nikhilgupta1891 so that appears to be an issue with your cucumber configuration, rather than this plugin. Those outputs are generated from cucumber “plugins”. Since you’re using Maven, I assume you’ve researched a Junit Runner class for cucumber. There you could configure the “json plugin” for cucumber. Check this out, hope it helps!

https://docs.cucumber.io/cucumber/reporting/
