### ISSUE TITLE
failed report causing net.masterthought.cucumber.ValidationException for Locale TR

### ISSUE THREAD

**Issue by dokmetas** [damianszczepanik/cucumber-reporting#837]
## Description
 A failed report causing the following exception for Locale TR;
```
net.masterthought.cucumber.ValidationException: File '/Users/Shared/Jenkins/Home/jobs/myScenario/builds/283/cucumber-html-reports/.cache/cucumber-reports/myJson.json' is not proper Cucumber report!
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:99)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:71)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:88)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:324)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:248)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No enum constant net.masterthought.cucumber.json.support.Status.FAİLED (through reference chain: java.lang.Object[][0]->net.masterthought.cucumber.json.Feature["elements"]->java.lang.Object[][1]->net.masterthought.cucumber.json.Element["steps"]->java.lang.Object[][13]->net.masterthought.cucumber.json.Step["result"]->net.masterthought.cucumber.json.Result["status"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1711)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3049)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:93)
	... 14 more
Caused by: java.lang.IllegalArgumentException: No enum constant net.masterthought.cucumber.json.support.Status.FAİLED
	at java.lang.Enum.valueOf(Enum.java:238)
	at net.masterthought.cucumber.json.support.Status.valueOf(Status.java:12)
	at net.masterthought.cucumber.json.deserializers.StatusDeserializer.deserialize(StatusDeserializer.java:28)
	at net.masterthought.cucumber.json.deserializers.StatusDeserializer.deserialize(StatusDeserializer.java:16)
	at net.masterthought.cucumber.json.deserializers.CucumberJsonDeserializer.deserialize(CucumberJsonDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	... 33 more
```

## Exception Stacktrace
https://gist.github.com/dokmetas/5dee5ad12c88fd95bff9fb8c47a069e9

## Environment
CurrentLocale is tr-TR

## Steps to Reproduce
Change default locale to tr-TR and generate report from json which includes FAILED steps.

## RCA
"Failed".upperCase() returns "FAİLED" for tr-TR which causes the exception described above.
More on that below;

"I".toLowerCase() returns "ı" not "i" for tr-TR locale.
"i".toUpperCase() returns "İ" not "I" for tr-TR locale.

**Comment by dokmetas** [comment]
Pull requested already : 
https://github.com/damianszczepanik/cucumber-reporting/pull/838
